version: '3.4'

volumes:
  tmp-data:

x-app: &app-service
  image: golang:1.15 # Image page: <https://hub.docker.com/_/golang>
  working_dir: /src
  environment:
    HOME: /tmp
    GOPATH: /tmp
  volumes:
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - .:/src:cached
    - tmp-data:/tmp:cached

services:
  app:
    <<: *app-service

  #web:
  #  <<: *app-service
  #  ports:
  #    - '8082:8080/tcp' # Open <http://127.0.0.1:8082>
  #  command: go run ./cmd/nod32-mirror serve --port 8080

  golint: # This is NOT application service, sources: <https://github.com/golangci/golangci-lint>
    image: golangci/golangci-lint:v1.31-alpine # Image page: <https://hub.docker.com/r/golangci/golangci-lint>
    volumes:
      - .:/app:ro
    working_dir: /app
    command: /bin/true
