version: "3"

services:
  backend:
    build: .
    volumes:
      - /path/to/storage/nod32mirror:/worker/nod32mirror:z
      - /optional/path/to/custom/settings.conf:/backend/settings.conf:ro

  frontend:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - /path/to/storage/nod32mirror:/nod32mirror:ro
      - ./nginx.server.conf:/etc/nginx/conf.d/default.conf:ro
