FROM alpine:latest

# We are going to use common GID (+better UID) to share files on the volume.
ARG UID
ARG GID

WORKDIR /backend

ADD ./nod32-mirror ./crontab.conf ./.nod32keys ./
# remove ./.nod32keys !

RUN addgroup -g ${GID} workers\
 && adduser -D -u ${UID} -G workers worker\
 && apk --no-cache --update add bash unrar curl\
 && crontab -u worker ./crontab.conf\
# && chmod -R +r ./\
 && chmod +x ./nod32-mirror.sh ./include/*.sh\
 
 # remove me
 && mkdir /nod32mirror && chown worker:workers /nod32mirror

USER worker
ENTRYPOINT ["/backend/nod32-mirror.sh", "--update"]
#CMD ["/usr/sbin/crond", "-f", "-d", "0"]
