#!/usr/bin/env bash

SCHEDULE_COMMAND="${*:-echo 'scheduler ticked'}";
FIRST_START_DELAY="${FIRST_START_DELAY:-1}";
SCHEDULE_PERIOD="${SCHEDULE_PERIOD:-5}";
START_BEFORE_LOOP="${START_BEFORE_LOOP:-true}";
WRITE_NOD32MIRROR_CONFIG_PATH="${WRITE_NOD32MIRROR_CONFIG_PATH:-/src/conf.d}";

STDOUT="${STDOUT:-/proc/1/fd/1}";
STDERR="${STDERR:-/proc/1/fd/2}";

trap "echo SIGHUP" HUP
trap "echo Shutting down; exit" TERM

# Execute command function
function execute_command() {
  ${SCHEDULE_COMMAND} > ${STDOUT} 2> ${STDERR};
}

echo -e "
export NOD32MIRROR_DEBUG_MODE=${NOD32MIRROR_DEBUG_MODE:-0};
export NOD32MIRROR_COLOR_OUTPUT=${NOD32MIRROR_COLOR_OUTPUT:-1};
export NOD32MIRROR_USE_FREE_KEY=${NOD32MIRROR_USE_FREE_KEY:-1};
export NOD32MIRROR_MIRROR_DIR=\"${NOD32MIRROR_MIRROR_DIR:-/data}\";
export NOD32MIRROR_TEMP_DIR=\"${NOD32MIRROR_TEMP_DIR:-/tmp}\";
export NOD32MIRROR_URI_PATH=\"${NOD32MIRROR_URI_PATH:-}\";
export NOD32MIRROR_SERVER_0=\"${NOD32MIRROR_SERVER_0:-http://update.eset.com:80/eset_upd/ username password}\";
export NOD32MIRROR_SERVER_1=\"${NOD32MIRROR_SERVER_1:-}\";
export NOD32MIRROR_SERVER_2=\"${NOD32MIRROR_SERVER_2:-}\";
export NOD32MIRROR_SERVER_3=\"${NOD32MIRROR_SERVER_3:-}\";
export NOD32MIRROR_SERVER_4=\"${NOD32MIRROR_SERVER_4:-}\";
export NOD32MIRROR_SERVER_5=\"${NOD32MIRROR_SERVER_5:-}\";
export NOD32MIRROR_SERVER_6=\"${NOD32MIRROR_SERVER_6:-}\";
export NOD32MIRROR_SERVER_7=\"${NOD32MIRROR_SERVER_7:-}\";
export NOD32MIRROR_SERVER_8=\"${NOD32MIRROR_SERVER_8:-}\";
export NOD32MIRROR_SERVER_9=\"${NOD32MIRROR_SERVER_9:-}\";
export NOD32MIRROR_PLATFORMS=\"${NOD32MIRROR_PLATFORMS:-__ALL__}\";
export NOD32MIRROR_TYPES=\"${NOD32MIRROR_TYPES:-__ALL__}\";
export NOD32MIRROR_LANGUAGES=\"${NOD32MIRROR_LANGUAGES:-1033 1049}\";
export NOD32MIRROR_VERSIONS=\"${NOD32MIRROR_VERSIONS:-pcu 4 5 6}\";
export NOD32MIRROR_W10UPGRADE_ENABLED=${NOD32MIRROR_W10UPGRADE_ENABLED:-1};
export NOD32MIRROR_VERSION_FILE_CRLF=${NOD32MIRROR_VERSION_FILE_CRLF:-1};
export NOD32MIRROR_LOG_PATH=\"${NOD32MIRROR_LOG_PATH:-/var/log/nod32mirror.log}\";
#export NOD32MIRROR_CURL_BIN=\"${NOD32MIRROR_CURL_BIN:-false}\";
#export NOD32MIRROR_WGET_BIN=\"${NOD32MIRROR_WGET_BIN:-false}\";
#export NOD32MIRROR_TEST_URI=\"${NOD32MIRROR_TEST_URI:-http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup}\";
export NOD32MIRROR_DOWNLOAD_SPEED_LIMIT=${NOD32MIRROR_DOWNLOAD_SPEED_LIMIT:-2048};
export NOD32MIRROR_DOWNLOAD_DELAY=${NOD32MIRROR_DOWNLOAD_DELAY:-1};
#export NOD32MIRROR_USERAGENT=\"${NOD32MIRROR_USERAGENT:-ESS Update}\";
export NOD32MIRROR_TIMESTAMP_FILE_NAME=\"${NOD32MIRROR_TIMESTAMP_FILE_NAME:-lastevent.txt}\";
export NOD32MIRROR_VERSION_FILE_NAME=\"${NOD32MIRROR_VERSION_FILE_NAME:-version.txt}\";
" > "$WRITE_NOD32MIRROR_CONFIG_PATH/default.conf";

echo "INFO: Command to execute: \"$SCHEDULE_COMMAND\". Delay between executions: $SCHEDULE_PERIOD";

sleep "$FIRST_START_DELAY";

if [ "$START_BEFORE_LOOP" == "true" ]; then
  execute_command;
fi;

while :; do
  # Do not freeze on LARGE delay
  for (( i=1; i<=$SCHEDULE_PERIOD; i+=1)); do
    sleep 1;
  done;

  execute_command;
done;
